### ISSUE TITLE
Words no english will not display

### ISSUE THREAD

**Issue by wastee** [frankenjoe/pdfchords#2]
Words no english will not display. It just show some empty blocks.

**Comment by frankenjoe** [comment]
Could you please post the pro file that causes the issue? thx.

**Comment by wastee** [comment]
Thanks for your reply.

Here is my file:

{title: Anyong}
{subtitle: Faye Wong}

{comment: Verse}
就算[Am]天空再深 看不[G]出裂痕        眉[F]头  仍[G]聚满密[C]云      [E]
就算[Am]一屋暗灯 照不[G]穿我身        仍[Em]可反映你[Am]心
让这[Am]口烟跳升 我身[G]躯下沉        曾[F]多么想[G]多么想[C]贴 [E]近
你的[Am]心和眼 口和耳[Dm]亦没缘份     我都[Em]捉不[Am]紧

{comment: Pre-chorus}
害怕[C]悲剧重演 我的[G]命中命中       越美[F]丽的东西我[Em]越不可碰
历[C]史在重演 这么[G]烦嚣城中         没理[F]由 相恋可以[E]没有暗涌
其实[Am]我再去爱惜你[Em]又有何用      难道[F]这次我抱紧你[E]未必落空

{start_of_chorus}
{comment: Chorus}
仍[Am]静候着你说 我[Em]别错用神       什[F]么我 都[G]有预[Am]感
然后[C]睁不开[G]两眼 看[Em]命运光[Am]临    然后[F]天空又再[G]涌起密[Am]云
{end_of_chorus}

Here is the result:

[Imgur](http://i.imgur.com/1KKeZ3L.png)


I installed my local "GSView". It also can't show chinese. But i don't know how to fix it either.

**Comment by frankenjoe** [comment]
To convert cdr to ps the chordii tool is used:

http://www.chordii.org/

unfortunately, it does not support unicode. However, in their documentation they announce this as future work (last update 2016-07-07). You could ask these guys if they are working on it already and if a new release is planned in the near future.
